### ISSUE TITLE
Can't compile last commit f1eda8acff4de90fa3443478e66fff81e48a20ce

### ISSUE THREAD

**Issue by DMinsky** [datamachine/tg#4]
Ubuntu 14.04 LTS
3.13.0-29-generic #53-Ubuntu SMP Wed Jun 4 21:00:20 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

```
bin/generate -g types-header auto/scheme.tlo > auto/auto-types.h || rm auto/auto-types.h
gcc -I. -I. -I./tgl -g -O2  -I/usr/local/include -I/usr/include -I/usr/include  -I/usr/include/python2.6   -DHAVE_CONFIG_H -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-deprecated-declarations -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -Wno-unused-parameter -fPIC -c -MP -MD -MF dep/main.d -MQ objs/main.o -o objs/main.o main.c
In file included from /usr/include/python2.6/pyconfig.h:6,
                 from /usr/include/python2.6/Python.h:8,
                 from python-tg.h:24,
                 from main.c:79:
/usr/include/python2.6/pyconfig-64.h:1034:1: error: "_POSIX_C_SOURCE" redefined
In file included from /usr/include/stdio.h:28,
                 from main.c:24:
/usr/include/features.h:213:1: error: this is the location of the previous definition
make: *** [objs/main.o] Error 1
```

**Comment by Surye** [comment]
Yea, python 2 support is broken, I will fix it today, python 3 is my main target so I got that working first.

**Comment by Surye** [comment]
I have added many fixes to the build system. I am currently supporting/testing 2.7/3.4, and really have no interest in supporting 2.6 as it's been EOLed for years at this point. However, I would be happy to hear if it does work, can you try again?

**Comment by DMinsky** [comment]
Unfortunally, make ended with same result.

Also, I was wrong, this was result for make on CentOS release 6.5 (Final) 2.6.32-042stab093.5 #1 SMP Fri Dec 19 20:34:40 MSK 2014 x86_64 x86_64 x86_64 GNU/Linux with Python 2.6

But when I tryied to configure this for Ubuntu 14.04 with python 2.7 (python-dev installed). I get this

```
checking for python build information... 
checking for python3.4... python3.4
checking for main in -lpython3.4... no
checking for main in -lpython3.4m... no
checking for python3.3... (cached) python3.4
checking for main in -lpython3.4... (cached) no
checking for main in -lpython3.4m... (cached) no
checking for python3.2... (cached) python3.4
checking for main in -lpython3.4... (cached) no
checking for main in -lpython3.4m... (cached) no
checking for python3.1... (cached) python3.4
checking for main in -lpython3.4... (cached) no
checking for main in -lpython3.4m... (cached) no
checking for python3... (cached) python3.4
checking for main in -lpython3.4... (cached) no
checking for main in -lpython3.4m... (cached) no
checking for python2.7... (cached) python3.4
checking for main in -lpython3.4... (cached) no
checking for main in -lpython3.4m... (cached) no
checking for python2.6... (cached) python3.4
checking for main in -lpython3.4... (cached) no
checking for main in -lpython3.4m... (cached) no
checking for python2... (cached) python3.4
checking for main in -lpython3.4... (cached) no
checking for main in -lpython3.4m... (cached) no
checking for python... (cached) python3.4
checking for main in -lpython3.4... (cached) no
checking for main in -lpython3.4m... (cached) no
  results of the Python check:
    Binary:      python3.4
    Library:     no
    Include Dir: no
configure: error: No supported python lib version found. Try --disable-python
```

**Comment by Surye** [comment]
Ah, it found your python3.4 binary and hung on to that when checking for other dev libraries. I'll take a look at the autoconf for that.

**Comment by Surye** [comment]
faec9c should fix the configure issue.

**Comment by DMinsky** [comment]
Yep, configured and maked as well on python2.7 system. Maybe close this issue. But please add few lines in readme about supported python versions.

**Comment by DMinsky** [comment]
Oh, I installed python3.4 and try to make tg:

```
gcc -I. -I. -I./tgl -g -O2  -I/usr/local/include -I/usr/include -I/usr/include  -I/usr/local/include/python3.4m   -DHAVE_CONFIG_H -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-deprecated-declarations -fno-strict-aliasing -fno-omit-frame-pointer -ggdb -Wno-unused-parameter -fPIC -c -MP -MD -MF dep/loop.d -MQ objs/loop.o -o objs/loop.o loop.c
In file included from /usr/local/include/python3.4m/Python.h:8,
                 from python-tg.h:24,
                 from loop.c:63:
/usr/local/include/python3.4m/pyconfig.h:1390:1: error: "_GNU_SOURCE" redefined
loop.c:24:1: error: this is the location of the previous definition
make: *** [objs/loop.o] Error 1
```

**Comment by Surye** [comment]
Hmm, similar to your error on CentOS with Py2.6, looks like the error is not coming from my code but from the python headers. And it looks like you're using your own compiled python3.4 in /usr/local? Any reason on Ubuntu for not using the python3-dev package?

In my /usr/include/x86_64-linux-gnu/python3.4m/pyconfig.h file, which is the pyconfig.h used in my system, it checks the definition first:

```
/* Enable GNU extensions on systems that have them.  */
#ifndef _GNU_SOURCE
# define _GNU_SOURCE 1
#endif
```

I wonder if it's something about your build that is not compatible with the lib setup. Or I need to be doing something to support your python build configuration.

Thanks for the help in identifying issues!

**Comment by DMinsky** [comment]
Actually I'm using CentOS, so I installed python3.4m from sources, sorry for confusing (just sometimes I'm using Ubuntu for testing). BTW, I found duplicate in `/usr/local/include/python3.4m/pyconfig.h`

```
/* Enable GNU extensions on systems that have them.  */
#ifndef _GNU_SOURCE
# define _GNU_SOURCE 1
#endif
```

And below

```
/* Define on Linux to activate all library features */
#define _GNU_SOURCE 1
```

I have no idea how is that even possible in vanila python installation. Anyway, I commented second define, and after make got this error:

```
gcc objs/main.o objs/loop.o objs/interface.o objs/lua-tg.o objs/json-tg.o objs/python-tg.o objs/python-types.o libs/libtgl.a -L/usr/local/lib -L/usr/lib -L/usr/lib   -rdynamic -ggdb -levent -ljansson -lconfig -lz -levent -lrt -lm   -lreadline -llua-5.1  -ldl -lpython3.4m -lssl -lcrypto   -o bin/telegram-cli
/usr/local/lib/libpython3.4m.a(posixmodule.o): In function `posix_forkpty':
/home/dminsky/Python-3.4.3/./Modules/posixmodule.c:6109: undefined reference to `forkpty'
/usr/local/lib/libpython3.4m.a(posixmodule.o): In function `posix_openpty':
/home/dminsky/Python-3.4.3/./Modules/posixmodule.c:6020: undefined reference to `openpty'
collect2: ld returned 1 exit status
make: *** [bin/telegram-cli] Error 1
```

So, I just added -lutil in EXTRA_LIBS and everything was compiled as well!

**Comment by Surye** [comment]
I will take a look at why that is needed for you on CentOS and update the docs and close this. I can't help but wonder if python 2.6 would have worked for you with a similar fix. I'm gonna spin up a CentOS test vm and play with it a bit.

**Comment by Surye** [comment]
Found the issue, it really was python's fault. But now it should no longer require library modification.
